### ISSUE TITLE
Pathfinder 2e version

### ISSUE THREAD

**Issue by gandhi39** [Voldemalort/darker-vision-for-5e#3]
Congratulations for this great module! I tried to study the code in order to make a modified version for PF2 but could not understand it enough. Could you make a PF2 version or help me to modify yours to make it?

PF2 has darkvision ("darkness" becomes "bright light" with grayscale, as d&d 3.5e) and low-light vision ("darkness" **stays as "darkness"**, but "dim light" becomes "bright light"). 

Darkvision can be emulated by using "bright vision" and setting the scene to have 1.0 global darkness. It's not exactly grayscale but purplescale works fine. So no need to change "bright vision".

The problem is low-light vision. Your module makes "dim vision" render "dim light" as "bright light" along its radius. Is it possible to render "dim light" as "bright light" **without rendering "darkness" as "dim light"**?

Thanks

**Comment by Voldemalort** [comment]
Sorry for the late reply. The code I've written works because an existing blend mode happens to cause an overlapping dimvision area (rendered as a light source) to interact with existing light sources in a way that just works. To do more would require writing custom shaders, which I do not intend to undertake.

It's also important to note that 0.7.5 now renders vision in a completely new way which can not take advantage of existing blend modes and would also likely require custom shader code.
